export const authCopy = {
  fr: {
    loginEyebrow: 'Pensé pour l’agriculture marocaine', loginHero: 'La bonne machine est plus proche que vous ne le pensez.', loginHeroCopy: 'Réservez du matériel agricole fiable, gérez vos locations et faites avancer chaque chantier depuis un seul endroit.', verified: 'Propriétaires vérifiés', secure: 'Réservations sécurisées', welcome: 'Bon retour parmi nous', loginTitle: 'Connectez-vous à votre compte', loginSubtitle: 'Continuez à gérer votre matériel et vos réservations.', registered: 'Votre compte est prêt. Connectez-vous pour commencer.', email: 'Adresse e-mail', password: 'Mot de passe', passwordPh: 'Saisissez votre mot de passe', hidePassword: 'Masquer le mot de passe', showPassword: 'Afficher le mot de passe', signingIn: 'Connexion en cours…', signIn: 'Se connecter', newUser: 'Nouveau sur AgroNet ?', createAccount: 'Créer un compte', loginFailed: 'Connexion impossible. Vérifiez votre e-mail et votre mot de passe.',
    registerEyebrow: 'Rejoignez le réseau de matériel', registerHero: 'Plus de travail réalisé. Moins de machines immobilisées.', registerHeroCopy: 'Trouvez une machine quand vous en avez besoin ou transformez votre matériel en source de revenu.', community: 'Communauté de confiance', createKicker: 'Créez votre compte', registerTitle: 'Commencez avec AgroNet', registerSubtitle: 'Quelques informations maintenant, puis complétez votre profil plus tard.', profilePicture: 'Photo de profil', optional: 'facultatif', profileHint: 'Ajoutez une photo claire pour être facilement reconnu.', addPhoto: 'Ajouter une photo', changePhoto: 'Changer la photo', remove: 'Supprimer', choosePhoto: 'Choisir une photo de profil', preview: 'Aperçu de la photo', firstName: 'Prénom', lastName: 'Nom', confirmPassword: 'Confirmer le mot de passe', minimum: 'Au moins 6 caractères', repeat: 'Répétez le mot de passe', phone: 'Téléphone', address: 'Ville ou adresse', addressPh: 'Ex. Meknès', consent: 'J’accepte les Conditions d’utilisation et la Politique de confidentialité d’AgroNet.', creating: 'Création du compte…', already: 'Vous avez déjà un compte ?', photoSize: 'La photo doit faire moins de 3 Mo.', mismatch: 'Les mots de passe ne correspondent pas.', acceptTerms: 'Acceptez les conditions pour continuer.', registerFailed: 'Impossible de créer votre compte. Réessayez.', emailUsed: 'Cette adresse e-mail est déjà utilisée.',
    continue: 'Continuer', signUp: 'S’inscrire', with: 'avec', socialDisabled: 'La connexion sociale sera disponible après la configuration des fournisseurs.', socialSetup: 'Ajoutez les identifiants du fournisseur pour activer cette option', orEmail: 'ou utilisez votre e-mail', callbackMissing: 'La réponse de connexion sociale est absente. Réessayez.', callbackExpired: 'Ce lien de connexion a expiré ou a déjà été utilisé.', callbackError: 'Connexion impossible', callbackLoading: 'Sécurisation de votre session AgroNet', callbackWait: 'Votre compte est connecté. Un instant…', backLogin: 'Retour à la connexion'
  },
  en: {
    loginEyebrow:'Built for Moroccan agriculture',loginHero:'The right machine is closer than you think.',loginHeroCopy:'Book trusted agricultural equipment, manage rentals, and keep every job moving from one place.',verified:'Verified owners',secure:'Secure bookings',welcome:'Welcome back',loginTitle:'Sign in to your account',loginSubtitle:'Continue managing your equipment and bookings.',registered:'Your account is ready. Sign in to get started.',email:'Email address',password:'Password',passwordPh:'Enter your password',hidePassword:'Hide password',showPassword:'Show password',signingIn:'Signing you in…',signIn:'Sign in',newUser:'New to AgroNet?',createAccount:'Create an account',loginFailed:'Sign in failed. Check your email and password.',registerEyebrow:'Join the equipment network',registerHero:'More work done. Less equipment sitting still.',registerHeroCopy:'Find machines when needed or turn your equipment into reliable income.',community:'Trusted community',createKicker:'Create your account',registerTitle:'Start with AgroNet',registerSubtitle:'A few details now, then complete your profile later.',profilePicture:'Profile picture',optional:'optional',profileHint:'Add a clear photo to help people recognize you.',addPhoto:'Add photo',changePhoto:'Change photo',remove:'Remove',choosePhoto:'Choose profile picture',preview:'Profile preview',firstName:'First name',lastName:'Last name',confirmPassword:'Confirm password',minimum:'At least 6 characters',repeat:'Repeat password',phone:'Phone',address:'City or address',addressPh:'e.g. Meknès',consent:"I agree to AgroNet's Terms & Conditions and Privacy Policy.",creating:'Creating your account…',already:'Already have an account?',photoSize:'Your profile photo must be smaller than 3 MB.',mismatch:'The passwords do not match.',acceptTerms:'Accept the Terms & Conditions to continue.',registerFailed:'We could not create your account. Try again.',emailUsed:'This email address is already in use.',continue:'Continue',signUp:'Sign up',with:'with',socialDisabled:'Social sign-in becomes available after provider setup.',socialSetup:'Add provider credentials to enable this option',orEmail:'or use your email',callbackMissing:'The social sign-in response is missing. Try again.',callbackExpired:'This sign-in link expired or was already used.',callbackError:'We could not sign you in',callbackLoading:'Securing your AgroNet session',callbackWait:'Your account is connected. One quick moment…',backLogin:'Back to sign in'
  },
  ar: {
    loginEyebrow:'مصمم للفلاحة المغربية',loginHero:'الآلة المناسبة أقرب مما تتصور.',loginHeroCopy:'احجز معدات فلاحية موثوقة وأدر إيجاراتك وأعمالك من مكان واحد.',verified:'ملاك موثّقون',secure:'حجوزات آمنة',welcome:'مرحباً بعودتك',loginTitle:'سجّل الدخول إلى حسابك',loginSubtitle:'تابع إدارة معداتك وحجوزاتك.',registered:'حسابك جاهز. سجّل الدخول للبدء.',email:'البريد الإلكتروني',password:'كلمة المرور',passwordPh:'أدخل كلمة المرور',hidePassword:'إخفاء كلمة المرور',showPassword:'إظهار كلمة المرور',signingIn:'جارٍ تسجيل الدخول…',signIn:'تسجيل الدخول',newUser:'جديد في أغرونت؟',createAccount:'إنشاء حساب',loginFailed:'تعذر تسجيل الدخول. تحقق من البريد وكلمة المرور.',registerEyebrow:'انضم إلى شبكة المعدات',registerHero:'عمل أكثر. معدات متوقفة أقل.',registerHeroCopy:'اعثر على المعدات عند الحاجة أو حوّل معداتك إلى مصدر دخل.',community:'مجتمع موثوق',createKicker:'أنشئ حسابك',registerTitle:'ابدأ مع أغرونت',registerSubtitle:'بعض المعلومات الآن، ويمكنك إكمال ملفك لاحقاً.',profilePicture:'الصورة الشخصية',optional:'اختياري',profileHint:'أضف صورة واضحة ليسهل التعرف عليك.',addPhoto:'إضافة صورة',changePhoto:'تغيير الصورة',remove:'حذف',choosePhoto:'اختيار صورة شخصية',preview:'معاينة الصورة',firstName:'الاسم الشخصي',lastName:'الاسم العائلي',confirmPassword:'تأكيد كلمة المرور',minimum:'6 أحرف على الأقل',repeat:'أعد كتابة كلمة المرور',phone:'الهاتف',address:'المدينة أو العنوان',addressPh:'مثال: مكناس',consent:'أوافق على شروط الاستخدام وسياسة الخصوصية لأغرونت.',creating:'جارٍ إنشاء الحساب…',already:'لديك حساب بالفعل؟',photoSize:'يجب ألا تتجاوز الصورة 3 ميغابايت.',mismatch:'كلمتا المرور غير متطابقتين.',acceptTerms:'وافق على الشروط للمتابعة.',registerFailed:'تعذر إنشاء الحساب. حاول مجدداً.',emailUsed:'هذا البريد الإلكتروني مستخدم بالفعل.',continue:'متابعة',signUp:'إنشاء حساب',with:'عبر',socialDisabled:'ستتوفر المصادقة الاجتماعية بعد إعداد المزود.',socialSetup:'أضف بيانات المزود لتفعيل هذا الخيار',orEmail:'أو استخدم بريدك الإلكتروني',callbackMissing:'بيانات تسجيل الدخول الاجتماعي غير موجودة. حاول مجدداً.',callbackExpired:'انتهت صلاحية رابط الدخول أو تم استخدامه.',callbackError:'تعذر تسجيل الدخول',callbackLoading:'جارٍ تأمين جلسة أغرونت',callbackWait:'تم ربط حسابك. لحظة واحدة…',backLogin:'العودة إلى تسجيل الدخول'
  }
};

export const getAuthCopy = language => authCopy[language] || authCopy.fr;
