import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Banknote, CalendarDays, CheckCircle2, ClipboardCheck, Search, ShieldCheck, Tractor, Upload, UserCheck, Wrench } from 'lucide-react';
import { useLanguage } from '../../i18n/LanguageContext';
import '../PublicPages.css';

const copy={
  fr:{journey:'Rechercher → demander → travailler → terminer',title:'Un chemin clair, de la recherche du matériel à la fin du chantier.',intro:'AgroNet réunit dates, services, prix, confiance, paiement et réalisation dans un seul parcours.',find:'Trouver du matériel',list:'Publier une machine',selected:'Matériel sélectionné',dates:'Dates sélectionnées',protected:'Réservation protégée',next:'Réponse du propriétaire',renters:'Pour les agriculteurs et locataires',rentTitle:'Réservez une capacité, pas seulement une machine',rentCopy:'La demande décrit ce dont le chantier a réellement besoin.',renterSteps:[['Comparer de vraies annonces','Consultez photos, caractéristiques, prix, localisation, disponibilité et confiance.'],['Construire la demande','Choisissez les dates et le niveau de service nécessaire.'],['Vérifier chaque coût','Consultez prix, durée, caution, services et paiement avant l’envoi.'],['Suivre le chantier','Suivez acceptation, paiement, réalisation et avis depuis votre tableau de bord.']],owners:'Pour les propriétaires',ownerTitle:'Transformez le temps d’arrêt en utilisation productive',ownerCopy:'Vous gardez le contrôle de la machine, des travaux acceptés et de chaque réservation.',ownerSteps:[['Créer une annonce utile','Ajoutez de bonnes photos, les caractéristiques, services, prix et localisation.'],['Renforcer la confiance','Complétez votre profil, demandez la vérification et obtenez des avis.'],['Contrôler les demandes','Consultez le locataire, les dates, le travail, la surface et le lieu.'],['Terminer et être payé','Suivez le chantier jusqu’à la fin et gardez vos versements organisés.']],start:'Créer une annonce',statuses:'Comprendre les statuts',statusTitle:'Aucune zone floue après l’envoi',statusItems:[['Demandée','Le propriétaire vérifie les dates et le travail.'],['Planifiée','Le propriétaire et le paiement sont confirmés.'],['En cours','La location ou le service est en cours.'],['Terminée','Les deux parties clôturent et peuvent laisser un avis.']],cta:'Votre prochain chantier peut commencer ici',ctaTitle:'Parcourez du matériel avec des détails et des prix clairs.',open:'Ouvrir le marché'},
  en:{journey:'Search → request → work → complete',title:'A clear path from finding equipment to finishing the job.',intro:'AgroNet keeps dates, services, pricing, trust, payment, and completion in one workflow.',find:'Find equipment',list:'List a machine',selected:'Equipment selected',dates:'Dates selected',protected:'Booking protected',next:'Owner response next',renters:'For farmers and renters',rentTitle:'Book the capability, not just the machine',rentCopy:'The request captures what the job actually needs.',renterSteps:[['Compare real listings','Review photos, specifications, pricing, location, availability, and trust.'],['Build the request','Choose dates and the service level you need.'],['Review every cost','See price, duration, deposit, service, and payment before submitting.'],['Track the job','Follow approval, payment, completion, and review from your dashboard.']],owners:'For equipment owners',ownerTitle:'Put idle capacity to productive use',ownerCopy:'You control the machine, accepted work, and every booking.',ownerSteps:[['Create a useful listing','Add strong photos, specifications, services, pricing, and location.'],['Build owner trust','Complete your profile, request verification, and earn reviews.'],['Control requests','Review the renter, dates, work, field size, and location.'],['Complete and get paid','Track completion and keep payout details organized.']],start:'Start a listing',statuses:'What the statuses mean',statusTitle:'No mystery after clicking submit',statusItems:[['Requested','The owner reviews dates and work details.'],['Scheduled','Owner and payment steps are confirmed.'],['In progress','The rental or service is happening.'],['Completed','Both sides close the job and can review.']],cta:'Your next job can start here',ctaTitle:'Browse equipment with clear details and pricing.',open:'Open marketplace'},
  ar:{journey:'البحث ← الطلب ← العمل ← الإكمال',title:'مسار واضح من العثور على المعدات إلى إنهاء العمل.',intro:'يجمع أغرونت التواريخ والخدمات والأسعار والثقة والدفع والإنجاز في مسار واحد.',find:'اعثر على معدات',list:'انشر آلة',selected:'تم اختيار المعدات',dates:'تم اختيار التواريخ',protected:'الحجز محمي',next:'رد المالك هو التالي',renters:'للفلاحين والمستأجرين',rentTitle:'احجز القدرة وليس الآلة فقط',rentCopy:'يصف الطلب ما يحتاجه العمل فعلاً.',renterSteps:[['قارن الإعلانات الحقيقية','راجع الصور والمواصفات والأسعار والموقع والتوفر والثقة.'],['أنشئ الطلب','اختر التواريخ ومستوى الخدمة المطلوب.'],['راجع كل التكاليف','شاهد السعر والمدة والضمان والخدمة والدفع قبل الإرسال.'],['تابع العمل','تابع القبول والدفع والإنجاز والتقييم من لوحة التحكم.']],owners:'لملاك المعدات',ownerTitle:'حوّل وقت التوقف إلى استخدام منتج',ownerCopy:'تبقى متحكماً في الآلة والأعمال المقبولة وكل حجز.',ownerSteps:[['أنشئ إعلاناً مفيداً','أضف صوراً جيدة والمواصفات والخدمات والأسعار والموقع.'],['عزز الثقة','أكمل ملفك واطلب التحقق واجمع التقييمات.'],['تحكم في الطلبات','راجع المستأجر والتواريخ والعمل والمساحة والموقع.'],['أكمل واحصل على مستحقاتك','تابع الإنجاز ونظّم معلومات التحويل.']],start:'أنشئ إعلاناً',statuses:'معنى الحالات',statusTitle:'لا غموض بعد إرسال الطلب',statusItems:[['مطلوب','يراجع المالك التواريخ وتفاصيل العمل.'],['مجدول','تم تأكيد المالك وخطوات الدفع.'],['قيد التنفيذ','الإيجار أو الخدمة جارٍ.'],['مكتمل','يغلق الطرفان العمل ويمكنهما التقييم.']],cta:'يمكن أن يبدأ عملك القادم هنا',ctaTitle:'تصفح معدات بتفاصيل وأسعار واضحة.',open:'افتح السوق'}
};
const renterIcons=[Search,CalendarDays,ClipboardCheck,CheckCircle2];const ownerIcons=[Upload,UserCheck,CalendarDays,Banknote];
const Flow=({steps,icons})=><div className="workflow-list">{steps.map(([title,text],index)=><article key={title}><span className="workflow-number">{String(index+1).padStart(2,'0')}</span><span className="workflow-icon">{React.createElement(icons[index],{size:22})}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div>;

const HowItWorks=()=>{const{language}=useLanguage();const c=copy[language]||copy.fr;return <main className="public-page how-public-page">
  <section className="public-hero process-hero"><div className="public-shell public-hero-grid"><div className="public-hero-copy"><span className="public-kicker">{c.journey}</span><h1>{c.title}</h1><p>{c.intro}</p><div className="public-actions"><Link className="public-primary" to="/equipment">{c.find} <ArrowRight size={18}/></Link><Link className="public-text-link" to="/equipment/list">{c.list}</Link></div></div><div className="process-hero-panel"><div className="process-machine"><img src="/agronet-harvest-v2.webp" alt=""/><span><Tractor size={18}/> {c.selected}</span></div><div className="process-line"><i className="active"/><i className="active"/><i/><i/></div><div className="process-status"><span><CheckCircle2 size={17}/> {c.dates}</span><span><ShieldCheck size={17}/> {c.protected}</span><span><Wrench size={17}/> {c.next}</span></div></div></div></section>
  <section className="public-section"><div className="public-shell"><header className="public-section-heading"><span>{c.renters}</span><h2>{c.rentTitle}</h2><p>{c.rentCopy}</p></header><Flow steps={c.renterSteps} icons={renterIcons}/></div></section>
  <section className="public-section owner-workflow-section"><div className="public-shell owner-workflow-grid"><div className="public-section-heading light"><span>{c.owners}</span><h2>{c.ownerTitle}</h2><p>{c.ownerCopy}</p><Link className="public-primary pale" to="/equipment/list">{c.start} <ArrowRight size={18}/></Link></div><Flow steps={c.ownerSteps} icons={ownerIcons}/></div></section>
  <section className="public-section"><div className="public-shell"><header className="public-section-heading"><span>{c.statuses}</span><h2>{c.statusTitle}</h2></header><div className="status-journey">{c.statusItems.map(([title,text],index)=><React.Fragment key={title}><div><span>{index+1}</span><strong>{title}</strong><small>{text}</small></div>{index<c.statusItems.length-1&&<ArrowRight/>}</React.Fragment>)}</div></div></section>
  <section className="public-final-cta"><div className="public-shell"><div><span>{c.cta}</span><h2>{c.ctaTitle}</h2></div><Link to="/equipment">{c.open} <ArrowRight size={18}/></Link></div></section>
</main>};

export default HowItWorks;
