const copy = {
  fr: {
    machines:'machines',categories:'catégories',verifiedOwners:'propriétaires vérifiés',average:'note moyenne',yourListing:'Votre annonce',day:'jour',noDescription:'Aucune description ajoutée.',delivery:'Livraison',instant:'Réservation instantanée',insured:'Assuré',serviced:'Entretien récent',listedBy:'Publié par',you:'Vous',verifiedOwner:'Propriétaire vérifié',hires:'locations terminées',newOwner:'Nouveau propriétaire',manage:'Gérer',reserve:'Réserver',unavailable:'Indisponible',removeFavorite:'Retirer des favoris',addFavorite:'Ajouter aux favoris',today:'Disponible aujourd’hui',tomorrow:'Disponible demain',bookedUntil:'Réservé jusqu’au',gps:'GPS intégré',specs:'Caractéristiques du matériel',
    filterTitle:'Filtrer le matériel',match:'résultat',matches:'résultats',reset:'Réinitialiser',close:'Fermer les filtres',suggestions:'Suggestions de recherche',search:'Rechercher une machine, un type ou une ville',clearSearch:'Effacer la recherche',whereWhen:'Où et quand',city:'Ville',allCities:'Toutes les villes',from:'Du',to:'Au',machineType:'Type de machine',noTypes:'Aucun type disponible.',more:'Plus de filtres',brand:'Marque',allBrands:'Toutes les marques',fuel:'Carburant',anyFuel:'Tous les carburants',transmission:'Transmission',anyTransmission:'Toutes',minHp:'Puissance min.',maxHp:'Puissance max.',deliveryAvailable:'Livraison disponible',instantBooking:'Réservation instantanée',verifiedOnly:'Propriétaires vérifiés uniquement',minimumRating:'Note minimale du propriétaire',anyRating:'Toutes les notes',andAbove:'et plus',budget:'Budget journalier',minimum:'Minimum',maximum:'Maximum',apply:'Appliquer les filtres',filters:'Filtres'
  },
  en: {
    machines:'machines',categories:'categories',verifiedOwners:'verified owners',average:'average rating',yourListing:'Your listing',day:'day',noDescription:'No description added yet.',delivery:'Delivery',instant:'Instant booking',insured:'Insured',serviced:'Recently serviced',listedBy:'Listed by',you:'You',verifiedOwner:'Verified owner',hires:'completed hires',newOwner:'New owner',manage:'Manage',reserve:'Reserve',unavailable:'Unavailable',removeFavorite:'Remove from favorites',addFavorite:'Add to favorites',today:'Available today',tomorrow:'Available tomorrow',bookedUntil:'Booked until',gps:'GPS ready',specs:'Equipment specifications',filterTitle:'Filter equipment',match:'match',matches:'matches',reset:'Reset',close:'Close filters',suggestions:'Search suggestions',search:'Search machine, type, or city',clearSearch:'Clear search',whereWhen:'Where and when',city:'City',allCities:'All cities',from:'From',to:'To',machineType:'Machine type',noTypes:'No equipment types available.',more:'More filters',brand:'Brand',allBrands:'All brands',fuel:'Fuel type',anyFuel:'Any fuel',transmission:'Transmission',anyTransmission:'Any transmission',minHp:'Min HP',maxHp:'Max HP',deliveryAvailable:'Delivery available',instantBooking:'Instant booking',verifiedOnly:'Verified owners only',minimumRating:'Minimum owner rating',anyRating:'Any rating',andAbove:'and above',budget:'Daily budget',minimum:'Minimum',maximum:'Maximum',apply:'Apply filters',filters:'Filters'
  },
  ar: {
    machines:'معدات',categories:'فئات',verifiedOwners:'ملاك موثّقون',average:'متوسط التقييم',yourListing:'إعلانك',day:'يوم',noDescription:'لم تتم إضافة وصف.',delivery:'التوصيل',instant:'حجز فوري',insured:'مؤمّنة',serviced:'صيانة حديثة',listedBy:'نشرها',you:'أنت',verifiedOwner:'مالك موثّق',hires:'إيجارات مكتملة',newOwner:'مالك جديد',manage:'إدارة',reserve:'حجز',unavailable:'غير متاحة',removeFavorite:'إزالة من المفضلة',addFavorite:'إضافة إلى المفضلة',today:'متاحة اليوم',tomorrow:'متاحة غداً',bookedUntil:'محجوزة حتى',gps:'مجهزة بـ GPS',specs:'مواصفات المعدات',filterTitle:'تصفية المعدات',match:'نتيجة',matches:'نتائج',reset:'إعادة ضبط',close:'إغلاق الفلاتر',suggestions:'اقتراحات البحث',search:'ابحث عن آلة أو نوع أو مدينة',clearSearch:'مسح البحث',whereWhen:'المكان والتاريخ',city:'المدينة',allCities:'كل المدن',from:'من',to:'إلى',machineType:'نوع الآلة',noTypes:'لا توجد أنواع متاحة.',more:'فلاتر إضافية',brand:'العلامة',allBrands:'كل العلامات',fuel:'الوقود',anyFuel:'كل أنواع الوقود',transmission:'ناقل الحركة',anyTransmission:'الكل',minHp:'القدرة الدنيا',maxHp:'القدرة القصوى',deliveryAvailable:'التوصيل متاح',instantBooking:'حجز فوري',verifiedOnly:'الملاك الموثّقون فقط',minimumRating:'الحد الأدنى للتقييم',anyRating:'كل التقييمات',andAbove:'فما فوق',budget:'الميزانية اليومية',minimum:'الحد الأدنى',maximum:'الحد الأقصى',apply:'تطبيق الفلاتر',filters:'الفلاتر'
  }
};

export const getMarketplaceCopy = language => copy[language] || copy.fr;
