import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Combine, Handshake, Leaf, MapPin, ShieldCheck, Sprout, Tractor, UsersRound } from 'lucide-react';
import { useLanguage } from '../../i18n/LanguageContext';
import '../PublicPages.css';

const copy = {
  fr:{kicker:'Pourquoi AgroNet existe',title:'Une bonne machine ne devrait jamais rester immobile lorsqu’un champ voisin en a besoin.',intro:'AgroNet relie les agriculteurs qui cherchent du matériel aux propriétaires capables de le partager. Le résultat : un accès pratique, des revenus locaux et des communautés agricoles plus productives.',explore:'Explorer le marché',how:'Comment ça marche',note:'Accès local. Valeur partagée.',noteCopy:'Des équipements plus utiles à toute la communauté.',constraint:'Né d’une contrainte réelle',access:'L’accès compte plus que la propriété',story:['Pour de nombreux travaux agricoles, acheter une machine est difficile à justifier. Le travail dure quelques jours, mais le coût et l’entretien restent pendant des années.','AgroNet comble cet écart. Les locataires disposent des détails nécessaires pour choisir, et les propriétaires d’un cadre clair pour présenter, planifier et gérer leur matériel.'],principles:'Nos principes',trust:'Une confiance utile, pas du décor',trustCopy:'Chaque décision doit rendre une transaction agricole plus claire ou plus sûre.',cards:[['La confiance est visible','Profils vérifiés, avis après les travaux et étapes de réservation traçables.'],['Le local d’abord','Le matériel proche réduit le transport et conserve la valeur dans les communautés agricoles.'],['Utiliser plutôt que gaspiller','Le partage améliore l’utilisation des machines sans imposer le même investissement à chaque ferme.'],['Les deux parties comptent','Le parcours doit protéger le locataire comme le propriétaire de la machine.']],network:'Un réseau, de nombreux travaux',season:'De la préparation du sol à la récolte',seasonCopy:'AgroNet accompagne les combinaisons de matériel et de services dont le travail agricole a réellement besoin.',tags:['Tracteurs','Moissonneuses','Entretien des cultures','Opérateurs'],action:'Le réseau en action',actionTitle:'Trouvez la machine dont votre prochain chantier a besoin.',browse:'Parcourir le matériel'},
  en:{kicker:'Why AgroNet exists',title:'Good machinery should never sit idle while a nearby field waits.',intro:'AgroNet connects farmers who need equipment with owners who can share capacity—creating practical access, local income, and more productive communities.',explore:'Explore the marketplace',how:'How it works',note:'Local access. Shared value.',noteCopy:'Equipment working harder for the whole community.',constraint:'Built around a real constraint',access:'Access matters more than ownership',story:['For many jobs, buying a machine is difficult to justify. Work may last days while cost and maintenance last for years.','AgroNet closes that gap, helping renters choose confidently and owners present, schedule, and manage machinery.'],principles:'Our operating principles',trust:'Useful trust, not marketplace theatre',trustCopy:'Every decision should make an agricultural transaction clearer or safer.',cards:[['Trust is visible','Verified profiles, completed-work reviews, and traceable booking states.'],['Local comes first','Nearby equipment reduces transport and keeps value inside farming communities.'],['Use beats waste','Sharing improves utilization without forcing every farm to carry the same investment.'],['Both sides matter','The workflow must protect renters and equipment owners alike.']],network:'One network, many jobs',season:'From soil preparation to harvest',seasonCopy:'AgroNet supports the equipment and service combinations real farm work requires.',tags:['Tractors','Harvesters','Crop care','Operators'],action:'See the network in action',actionTitle:'Find the machine your next job needs.',browse:'Browse equipment'},
  ar:{kicker:'لماذا وُجد أغرونت',title:'لا ينبغي لآلة جيدة أن تبقى متوقفة بينما يحتاجها حقل قريب.',intro:'يربط أغرونت الفلاحين الباحثين عن المعدات بالملاك القادرين على مشاركتها، مما يخلق وصولاً عملياً ودخلاً محلياً ومجتمعات أكثر إنتاجية.',explore:'استكشف السوق',how:'كيف يعمل',note:'وصول محلي. قيمة مشتركة.',noteCopy:'معدات تعمل أكثر لصالح المجتمع.',constraint:'مبني حول تحدٍّ حقيقي',access:'الوصول أهم من الامتلاك',story:['في كثير من الأعمال يصعب تبرير شراء آلة لا تُستخدم إلا أياماً بينما تستمر تكاليفها سنوات.','يسد أغرونت هذه الفجوة، فيساعد المستأجر على الاختيار والمالك على عرض معداته وجدولتها وإدارتها.'],principles:'مبادئنا',trust:'ثقة مفيدة وليست مجرد مظهر',trustCopy:'يجب أن يجعل كل قرار المعاملة أوضح أو أكثر أماناً.',cards:[['الثقة ظاهرة','ملفات موثقة وتقييمات بعد العمل وحجوزات قابلة للتتبع.'],['الأولوية للمحلي','المعدات القريبة تقلل النقل وتحافظ على القيمة داخل المجتمع.'],['الاستخدام أفضل من الهدر','المشاركة ترفع الاستفادة دون فرض الاستثمار نفسه على كل مزرعة.'],['الطرفان مهمان','يجب أن يحمي المسار المستأجر ومالك المعدات معاً.']],network:'شبكة واحدة، أعمال متعددة',season:'من إعداد التربة إلى الحصاد',seasonCopy:'يدعم أغرونت المعدات والخدمات التي يحتاجها العمل الفلاحي فعلاً.',tags:['جرارات','حصادات','العناية بالمحاصيل','مشغلون'],action:'شاهد الشبكة تعمل',actionTitle:'اعثر على الآلة التي يحتاجها عملك القادم.',browse:'تصفح المعدات'}
};

const About=()=>{const{language}=useLanguage();const c=copy[language]||copy.fr;const icons=[ShieldCheck,MapPin,Leaf,UsersRound];const tagIcons=[Tractor,Combine,Sprout,UsersRound];return <main className="public-page about-public-page">
  <section className="public-hero about-hero"><div className="public-shell public-hero-grid"><div className="public-hero-copy"><span className="public-kicker">{c.kicker}</span><h1>{c.title}</h1><p>{c.intro}</p><div className="public-actions"><Link className="public-primary" to="/equipment">{c.explore} <ArrowRight size={18}/></Link><Link className="public-text-link" to="/how-it-works">{c.how}</Link></div></div><div className="public-hero-image about-hero-image"><img src="/agronet-community-v2.webp" alt=""/><div className="public-image-note"><Handshake size={22}/><span><strong>{c.note}</strong><small>{c.noteCopy}</small></span></div></div></div></section>
  <section className="public-section"><div className="public-shell public-story-grid"><div className="public-section-heading"><span>{c.constraint}</span><h2>{c.access}</h2></div><div className="public-story-copy"><p>{c.story[0]}</p><p>{c.story[1]}</p></div></div></section>
  <section className="public-section public-dark-section"><div className="public-shell"><header className="public-section-heading light"><span>{c.principles}</span><h2>{c.trust}</h2><p>{c.trustCopy}</p></header><div className="principle-grid">{c.cards.map(([title,text],index)=><article key={title}>{React.createElement(icons[index],{size:25})}<h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="public-section"><div className="public-shell public-ecosystem"><div><span className="public-kicker">{c.network}</span><h2>{c.season}</h2><p>{c.seasonCopy}</p><div className="ecosystem-tags">{c.tags.map((tag,index)=><span key={tag}>{React.createElement(tagIcons[index],{size:18})} {tag}</span>)}</div></div><img src="/agronet-harvest-v2.webp" alt=""/></div></section>
  <section className="public-final-cta"><div className="public-shell"><div><span>{c.action}</span><h2>{c.actionTitle}</h2></div><Link to="/equipment">{c.browse} <ArrowRight size={18}/></Link></div></section>
</main>};

export default About;
